CREATE TABLE public.covid_deaths (
    iso_code CHAR(10),
    continent CHAR(20),
    location VARCHAR(50),
    date TIMESTAMP,
    population BIGINT,
    total_cases BIGINT,
    new_cases DECIMAL,
    new_cases_smoothed DECIMAL,
    total_deaths BIGINT,
    new_deaths BIGINT,
    new_deaths_smoothed DECIMAL,
    total_cases_per_million DECIMAL,
    new_cases_per_million DECIMAL,
    new_cases_smoothed_per_million DECIMAL,
    total_deaths_per_million DECIMAL,
    new_deaths_per_million DECIMAL,
    new_deaths_smoothed_per_million DECIMAL,
    reproduction_rate DECIMAL,
    icu_patients INT,
    icu_patients_per_million DECIMAL,
    hosp_patients INT,
    hosp_patients_per_million DECIMAL,
    weekly_icu_admissions INT,
    weekly_icu_admissions_per_million DECIMAL,
    weekly_hosp_admissions INT,
    weekly_hosp_admissions_per_million DECIMAL
) 

CREATE TABLE public.covid_vaccinations (
    iso_code CHAR(10),
    continent CHAR(20),
    location VARCHAR(50),
    date TIMESTAMP,
    total_tests BIGINT,
    new_tests BIGINT,
    total_tests_per_thousand DECIMAL,
    new_tests_per_thousand DECIMAL,
    new_tests_smoothed BIGINT,
    new_tests_smoothed_per_thousand DECIMAL,
    positive_rate DECIMAL,
    tests_per_case DECIMAL,
    tests_units TEXT,
    total_vaccinations BIGINT,
    people_vaccinated BIGINT,
    people_fully_vaccinated BIGINT,
    total_boosters BIGINT,
    new_vaccinations BIGINT,
    new_vaccinations_smoothed BIGINT,
    total_vaccinations_per_hundred DECIMAL,
    people_vaccinated_per_hundred DECIMAL,
    people_fully_vaccinated_per_hundred DECIMAL,
    total_boosters_per_hundred DECIMAL,
    new_vaccinations_smoothed_per_million BIGINT,
    new_people_vaccinated_smoothed BIGINT,
    new_people_vaccinated_smoothed_per_hundred DECIMAL,
    stringency_index DECIMAL,
    population_density DECIMAL,
    median_age DECIMAL,
    aged_65_older DECIMAL,
    aged_70_older DECIMAL,
    gdp_per_capita DECIMAL,
    extreme_poverty DECIMAL,
    cardiovasc_death_rate DECIMAL,
    diabetes_prevalence DECIMAL,
    female_smokers DECIMAL,
    male_smokers DECIMAL,
    handwashing_facilities DECIMAL,
    hospital_beds_per_thousand DECIMAL,
    life_expectancy DECIMAL,
    human_development_index DECIMAL,
    excess_mortality_cumulative_absolute DECIMAL,
    excess_mortality_cumulative DECIMAL,
    excess_mortality DECIMAL,
    excess_mortality_cumulative_per_million DECIMAL
) 

DROP TABLE covid_vaccinations;